name: Code Quality

on:
  push:
    branches:
      - main
      - develop

jobs:
  code-quality:
    runs-on: [self-hosted, linux, x64, github-runner-lxc]

    strategy:
      matrix:
        php-version: [8.2, 8.4]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, pdo_mysql
          tools: composer

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --no-progress

      - name: Run Laravel Pint
        run: |
          ./vendor/bin/pint
          git add .
          git diff-index --quiet HEAD || (echo "::error::Code style issues found and fixed. Please commit them locally." && exit 1)

      - name: Run Larastan
        run: ./vendor/bin/phpstan analyse --memory-limit=2G
